# editor completions
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

[line_break]
disabled = false

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[nodejs]
detect_files = [ "package.json", ".node-version", ".nvmrc", "!bun.lockb" ]