import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[window]
padding = { x = 16, y = 10 }
opacity = 0.90
blur = true

[font]
size = 13
normal = { family = "JetBrainsMono NF", style = "regular" }

[cursor]
style = { blinking = "On", shape = "Underline" }
